export const ACCESSIBILITY: Record<string, string> = {
  handrail: 'IN_ACESSIBILIDADE_CORRIMAO',
  elevator: 'IN_ACESSIBILIDADE_ELEVADOR',
  tactile_flooring: 'IN_ACESSIBILIDADE_PISOS_TATEIS',
  clearance_space: 'IN_ACESSIBILIDADE_VAO_LIVRE',
  ramps: 'IN_ACESSIBILIDADE_RAMPAS',
  audible_signal: 'IN_ACESSIBILIDADE_SINAL_SONORO',
  tactile_signal: 'IN_ACESSIBILIDADE_SINAL_TATIL',
  visual_signal: 'IN_ACESSIBILIDADE_SINAL_VISUAL',
}

export const INTERNET: Record<string, string> = {
  student_internet: 'IN_INTERNET_ALUNOS',
  administrative_internet: 'IN_INTERNET_ADMINISTRATIVO',
  learning_internet: 'IN_INTERNET_APRENDIZAGEM',
  community_internet: 'IN_INTERNET_COMUNIDADE',
  student_computer_internet: 'IN_ACESSO_INTERNET_COMPUTADOR',
  student_personal_device_internet: 'IN_ACES_INTERNET_DISP_PESSOAIS',
}

export const STAFF: Record<string, string> = {
  administrative_staff_count: 'QT_PROF_ADMINISTRATIVOS',
  general_services_count: 'QT_PROF_SERVICOS_GERAIS',
  librarian_count: 'QT_PROF_BIBLIOTECARIO',
  health_staff_count: 'QT_PROF_SAUDE',
  coordinator_count: 'QT_PROF_COORDENADOR',
  speech_therapist_count: 'QT_PROF_FONOAUDIOLOGO',
  nutritionist_count: 'QT_PROF_NUTRICIONISTA',
  psychologist_count: 'QT_PROF_PSICOLOGO',
  food_service_staff_count: 'QT_PROF_ALIMENTACAO',
  pedagogy_staff_count: 'QT_PROF_PEDAGOGIA',
  secretary_count: 'QT_PROF_SECRETARIO',
  security_staff_count: 'QT_PROF_SEGURANCA',
  monitor_count: 'QT_PROF_MONITORES',
  management_staff_count: 'QT_PROF_GESTAO',
  social_worker_count: 'QT_PROF_ASSIST_SOCIAL',
}

export const QUOTAS: Record<string, string> = {
  racial_ethnic_quota: 'IN_RESERVA_PPI',
  income_quota: 'IN_RESERVA_RENDA',
  public_school_quota: 'IN_RESERVA_PUBLICA',
  disability_quota: 'IN_RESERVA_PCD',
  other_quotas: 'IN_RESERVA_OUTROS',
}

export const INFRA_BOOL: Record<string, string> = {
  drinking_water: 'IN_AGUA_POTAVEL',
  storage_room: 'IN_ALMOXARIFADO',
  green_area: 'IN_AREA_VERDE',
  auditorium: 'IN_AUDITORIO',
  bathroom: 'IN_BANHEIRO',
  children_bathroom: 'IN_BANHEIRO_EI',
  accessible_bathroom: 'IN_BANHEIRO_PNE',
  staff_bathroom: 'IN_BANHEIRO_FUNCIONARIOS',
  shower_bathroom: 'IN_BANHEIRO_CHUVEIRO',
  library: 'IN_BIBLIOTECA',
  kitchen: 'IN_COZINHA',
  student_dormitory: 'IN_DORMITORIO_ALUNO',
  teacher_dormitory: 'IN_DORMITORIO_PROFESSOR',
  science_laboratory: 'IN_LABORATORIO_CIENCIAS',
  computer_laboratory: 'IN_LABORATORIO_INFORMATICA',
  covered_patio: 'IN_PATIO_COBERTO',
  open_patio: 'IN_PATIO_DESCOBERTO',
  playground: 'IN_PARQUE_INFANTIL',
  swimming_pool: 'IN_PISCINA',
  covered_sports_court: 'IN_QUADRA_ESPORTES_COBERTA',
  open_sports_court: 'IN_QUADRA_ESPORTES_DESCOBERTA',
  arts_room: 'IN_SALA_ATELIE_ARTES',
  music_room: 'IN_SALA_MUSICA_CORAL',
  dance_room: 'IN_SALA_ESTUDIO_DANCA',
  recreation_room: 'IN_SALA_MULTIUSO',
  principal_office: 'IN_SALA_DIRETORIA',
  reading_room: 'IN_SALA_LEITURA',
  teacher_room: 'IN_SALA_PROFESSOR',
  student_rest_room: 'IN_SALA_REPOUSO_ALUNO',
  secretary_office: 'IN_SECRETARIA',
  special_needs_room: 'IN_SALA_ATENDIMENTO_ESPECIAL',
  recreational_field: 'IN_TERREIRAO',
  meal_service: 'IN_ALIMENTACAO',
  social_media: 'IN_REDES_SOCIAIS',
}

export const INFRA_INT: Record<string, string> = {
  classroom_count: 'QT_SALAS_UTILIZADAS',
  outdoor_classroom_count: 'QT_SALAS_UTILIZADAS_FORA',
  indoor_classroom_count: 'QT_SALAS_UTILIZADAS_DENTRO',
  air_conditioned_classroom_count: 'QT_SALAS_UTILIZA_CLIMATIZADAS',
  accessible_classroom_count: 'QT_SALAS_UTILIZADAS_ACESSIVEIS',
  dvd_player_count: 'QT_EQUIP_DVD',
  sound_system_count: 'QT_EQUIP_SOM',
  tv_count: 'QT_EQUIP_TV',
  digital_whiteboard_count: 'QT_EQUIP_LOUSA_DIGITAL',
  projector_count: 'QT_EQUIP_MULTIMIDIA',
  desktop_computer_count: 'QT_DESKTOP_ALUNO',
  laptop_count: 'QT_COMP_PORTATIL_ALUNO',
  tablet_count: 'QT_TABLET_ALUNO',
}

export const EDUCATION_BOOL: Record<string, string> = {
  indigenous_education: 'IN_EDUCACAO_INDIGENA',
  entrance_exam: 'IN_EXAME_SELECAO',
  student_council: 'IN_ORGAO_GREMIO_ESTUDANTIL',
  distance_learning: 'IN_EAD',
}

export const EDUCATION_INT: Record<string, string> = {
  early_childhood_enrollment_count: 'QT_MAT_INF',
  early_childhood_teacher_count: 'QT_DOC_INF',
  nursery_enrollment_count: 'QT_MAT_INF_CRE',
  nursery_teacher_count: 'QT_DOC_INF_CRE',
  preschool_enrollment_count: 'QT_MAT_INF_PRE',
  preschool_teacher_count: 'QT_DOC_INF_PRE',
  elementary_enrollment_count: 'QT_MAT_FUND',
  elementary_teacher_count: 'QT_DOC_FUND',
  early_elementary_enrollment_count: 'QT_MAT_FUND_AI',
  early_elementary_teacher_count: 'QT_DOC_FUND_AI',
  late_elementary_enrollment_count: 'QT_MAT_FUND_AF',
  late_elementary_teacher_count: 'QT_DOC_FUND_AF',
  high_school_enrollment_count: 'QT_MAT_MED',
  high_school_teacher_count: 'QT_DOC_MED',
  technical_high_school_enrollment_count: 'QT_MAT_MED_CT',
  technical_high_school_teacher_count: 'QT_DOC_MED_CT',
  vocational_enrollment_count: 'QT_MAT_PROF',
  vocational_teacher_count: 'QT_DOC_PROF',
  technical_enrollment_count: 'QT_MAT_PROF_TEC',
  technical_teacher_count: 'QT_DOC_PROF_TEC',
  adult_education_enrollment_count: 'QT_MAT_EJA',
  adult_education_teacher_count: 'QT_DOC_EJA',
  adult_elementary_enrollment_count: 'QT_MAT_EJA_FUND',
  adult_elementary_teacher_count: 'QT_DOC_EJA_FUND',
  adult_early_elementary_enrollment_count: 'QT_MAT_EJA_FUND_AI',
  adult_early_elementary_teacher_count: 'QT_DOC_EJA_FUND_AI',
  adult_late_elementary_enrollment_count: 'QT_MAT_EJA_FUND_AF',
  adult_late_elementary_teacher_count: 'QT_DOC_EJA_FUND_AF',
  adult_high_school_enrollment_count: 'QT_MAT_EJA_MED',
  adult_high_school_teacher_count: 'QT_DOC_EJA_MED',
  special_education_enrollment_count: 'QT_MAT_ESP',
  special_education_teacher_count: 'QT_DOC_ESP',
}
